### ISSUE TITLE
If both the dividend and the divisor are negative, the output will be negative

### ISSUE THREAD

**Issue by AGuyNamedTal** [AdamWhiteHat/BigRational#1]
For example, if you divide -1 by -1 you get -1 (you should really get 1)

**Comment by AdamWhiteHat** [comment]
@AGuyNamedTal 
I fixed this and added a test method to the test project asserting that this is the case. Thank you for catching this.

As an aside, I would recommend using my BigDecimal class instead of this one, if that would still be appropriate for your needs, as it is has been tested and used far more thoroughly than this class.  Also, I am unsure about my decision to write this as two classes, with a Fraction class and a BigRational class that holds a whole number
and a fraction. This could all be simplified into just a fraction class that allows improper fractions. I was thinking about scraping it, but I guess that is unnecessary, because if I do decide to make a simplified version, I can just name it BigFraction or something instead. Do you have any input/thoughts/philosophical rebuttals regarding this?

Thanks again, and sorry I took so long to get around to fixing this.
