### ISSUE TITLE
BUG: Sqrt result in diff from calculator

### ISSUE THREAD

**Issue by kentsday** [AdamWhiteHat/BigRational#12]
**Description**

```cs
[Test]
public void BigRationTest()
{
    var a = new BigRational(BigInteger.Parse("160000000000"));
    var b = new BigRational(BigInteger.Parse("249"), new Fraction(0.999));
    var c = BigRational.Divide(a, b);
    Console.WriteLine((decimal)c);
    Console.WriteLine(BigRational.Sqrt(c));
    // this result in 25348.917835671342685370741483M
    var bigRational = (decimal)BigRational.Sqrt(c);
    // this result in 25298.271877941387183714739055M, it is the same as the result from calculator from PC or phone
    var cc = DecimalMath.DecimalEx.Sqrt(160000000000m / 249.999m);
    // failed
    cc.Should().Be(bigRational);
}
```

**Comment by AdamWhiteHat** [comment]
Thanks for bringing this to my attention. 
This is fixed now.

You can get the latest version on the main branch and build it yourself, of just grab the latest version of the nuget library:
[BigRational 2023.162.546](https://www.nuget.org/packages/ExtendedNumerics.BigRational/2023.162.546)

You will notice the Sqrt function now comes with an optional precision parameter. This is the minimum number of decimal digits the rational approximation (presuming the result is a irrational number) must be good to. Its default value is 30. Increasing the precision parameter comes at the cost of larger and larger numerators and denominators in the fractional part.

You can close this issue if you are satisfied, otherwise I will probably close this issue if I don't hear anything from you in about week or so.

**Comment by kentsday** [comment]
verified for version 2023.162.546. it works, thanks
