### ISSUE TITLE
BUG: operator +(BigRational rational) is mathematically incorrect

### ISSUE THREAD

**Issue by carloscs** [AdamWhiteHat/BigRational#14]
public static BigRational operator +(BigRational rational) => Abs(rational);

Thats's mathematically incorrect: "+ (-5)" equals "-5" not "5"

Should be:

public static BigRational operator +(BigRational rational) => rational;

**Comment by AdamWhiteHat** [comment]
Yep; You're right. 
I don't know where I got the idea that the unary plus operator was supposed to return the positive (non-negative) value of the operand but a quick look at Microsoft's language reference confirms this is not the correct behavior. Whoops.
This has been corrected and the main branch should now reflect this change. 
If you use NuGet packages, the new version that includes this correction is [2023.221.2134](https://www.nuget.org/packages/ExtendedNumerics.BigRational/2023.221.2134).

I also added 4 new tests to ensure the correct behavior is present and that it does not change in the future: A test for BigRational's unary plus, BigRational's unary minus, Fraction's unary plus, and Fraction's unary minus.

Thank you for bringing this to my attention. You not only helped make this library more correct, you helped me correct a misconception that I had about how unary plus is supposed to behave. 
I'll have to double check my other numeric type libraries, but so far they do not seem to have the same issue. 🤷

You can close this issue if you are satisfied that the bug is resolved, otherwise I will probably close this issue in about week or so if I don't hear anything else from you.

**Comment by AdamWhiteHat** [comment]
I'm going to go ahead and close this issue now. 

Thank you for your interest in my library and thank you for bringing this to my attention.

Feel free to open another issue if you don't feel this issue is resolved or you encounter any more defects.
